Sundsvallskommun/api-service-casemanagement

- src/main/java/se/sundsvall/casemanagement/api/CaseResource.java
- src/main/java/se/sundsvall/casemanagement/api/model/enums/CaseType.java
- src/main/java/se/sundsvall/casemanagement/integration/byggr/ByggrProcessor.java
- src/main/java/se/sundsvall/casemanagement/integration/byggr/ByggrService.java
- src/main/java/se/sundsvall/casemanagement/integration/casedata/CasedataProcessor.java
- src/main/java/se/sundsvall/casemanagement/integration/ecos/EcosProcessor.java
- src/main/java/se/sundsvall/casemanagement/service/util/Validator.java
- src/main/java/se/sundsvall/casemanagement/util/Processor.java
Sending feedback to OpenE if errand was not successfully created
> Correction to setting of ErrranClass value if facilityType is null

- src/main/java/se/sundsvall/casemanagement/integration/ecos/EcosService.java
- src/main/java/se/sundsvall/casemanagement/integration/ecos/RiskClassService.java
- src/test/java/se/sundsvall/casemanagement/service/ecos/RiskClassServiceTest.java
updated to handle nullvalue in subtitle, changed to look at facilitname and not facilityCollectionName
> Uf-5710 ,UF-5688

- src/integration-test/resources/CasedataIT/__files/test1_PostParkingPermitCase/mappings/casedata_postCase.json
- src/main/java/se/sundsvall/casemanagement/integration/casedata/CaseDataService.java
- src/main/java/se/sundsvall/casemanagement/integration/db/CaseMappingRepository.java
- src/main/java/se/sundsvall/casemanagement/service/CaseMappingService.java
- src/main/java/se/sundsvall/casemanagement/service/CaseService.java
- src/main/java/se/sundsvall/casemanagement/service/FbService.java
- src/main/java/se/sundsvall/casemanagement/service/mapper/CaseMapper.java
- src/main/java/se/sundsvall/casemanagement/service/mapper/CaseMappingMapper.java
- src/main/java/se/sundsvall/casemanagement/service/mapper/FbMapper.java
- src/test/java/se/sundsvall/casemanagement/TestUtil.java
- src/test/java/se/sundsvall/casemanagement/integration/byggr/ByggrProcessorTest.java
- src/test/java/se/sundsvall/casemanagement/integration/citizen/configuration/CitizenConfigurationTest.java
- src/test/java/se/sundsvall/casemanagement/service/ByggrServiceTest.java
- src/test/java/se/sundsvall/casemanagement/service/CaseDataServiceTest.java
- src/test/java/se/sundsvall/casemanagement/service/CaseMappingServiceTest.java
- src/test/java/se/sundsvall/casemanagement/service/EcosServiceTest.java
- src/test/java/se/sundsvall/casemanagement/service/FbServiceTest.java
- src/test/java/se/sundsvall/casemanagement/service/ecos/RiskClassServiceTest.java
- src/test/java/se/sundsvall/casemanagement/service/mapper/CaseMapperTest.java
- src/test/java/se/sundsvall/casemanagement/service/mapper/CaseMappingMapperTest.java
- src/test/java/se/sundsvall/casemanagement/service/mapper/FbMapperTest.java
- Extended casedata mapping with addition of channel attribute
- Refactored service classes and created mapper classes in mapper sub package for each service class
> UF-7651: Extended casedata mapping

- src/main/java/se/sundsvall/casemanagement/integration/ecos/EcosProcessor.java
- src/main/resources/application.yml
Remove obsolete property and fix possible long transactions spans.
> UF-9167: Bug fixes

- src/main/java/se/sundsvall/casemanagement/integration/byggr/ByggrMapper.java
> fixed attention on intressentKommunikation

- src/main/java/se/sundsvall/casemanagement/integration/byggr/ByggrMapper.java
- src/test/java/se/sundsvall/casemanagement/TestUtil.java
- src/test/java/se/sundsvall/casemanagement/integration/byggr/ByggrMapperTest.java
- src/test/java/se/sundsvall/casemanagement/integration/byggr/ByggrServiceTest.java
> updated attentions.

- src/main/java/se/sundsvall/casemanagement/integration/byggr/ByggrMapper.java
> Added a null check for stakeholder addresses

- src/integration-test/resources/AttachmentsIT/__files/test3_postCasedataAttachment/response/CaseData_GetErrandWithId.json
- src/integration-test/resources/CaseStatusIT/__files/test3_GetCaseDataStatusByExternalCaseId/response/CaseData_GetErrandWithId.json
- src/integration-test/resources/CasedataIT/__files/test1_PostParkingPermitCase/mappings/casedata_postCase.json
- src/integration-test/resources/CasedataIT/__files/test1_PostParkingPermitCase/response/casedata_getCase.json
- src/main/java/se/sundsvall/casemanagement/integration/casedata/CaseDataMapper.java
- src/main/resources/integrations/rest/case-data.yml
- src/test/java/se/sundsvall/casemanagement/integration/casedata/CaseDataMapperTest.java
- src/test/java/se/sundsvall/casemanagement/integration/casedata/CaseDataServiceTest.java
> UF-10441: Updated CaseData integration

- src/main/java/se/sundsvall/casemanagement/integration/byggr/ByggrMapper.java
- src/test/java/se/sundsvall/casemanagement/integration/byggr/ByggrMapperTest.java
> Minor changes to how the title is set in the byggr cases

- src/integration-test/resources/CasedataIT/__files/test2_postCaseInternalError/mappings/messaging_email.json
- src/integration-test/resources/CasedataIT/__files/test2_postCaseInternalError/mappings/messaging_slack.json
- src/integration-test/resources/EcosCreateCaseFailuresIT/__files/test3_Livsmedel500Response/mappings/messaging_email.json
- src/integration-test/resources/EcosCreateCaseFailuresIT/__files/test4_PropertyDesignationNotFound/mappings/messaging_email.json
- src/main/java/se/sundsvall/casemanagement/api/model/AddressDTO.java
- src/main/java/se/sundsvall/casemanagement/api/model/ByggRCaseDTO.java
- src/main/java/se/sundsvall/casemanagement/api/model/CoordinatesDTO.java
- src/main/java/se/sundsvall/casemanagement/api/model/EcosCaseDTO.java
- src/main/java/se/sundsvall/casemanagement/api/model/FacilityDTO.java
- src/main/java/se/sundsvall/casemanagement/api/model/OtherCaseDTO.java
- src/main/java/se/sundsvall/casemanagement/integration/byggr/ByggrProcessor.java
- src/main/java/se/sundsvall/casemanagement/integration/casedata/CasedataProcessor.java
- src/main/java/se/sundsvall/casemanagement/integration/ecos/EcosProcessor.java
- src/main/java/se/sundsvall/casemanagement/util/Processor.java
- src/test/java/se/sundsvall/casemanagement/api/CaseResourceFailureTest.java
- src/test/java/se/sundsvall/casemanagement/integration/byggr/ByggrProcessorTest.java
- src/test/java/se/sundsvall/casemanagement/integration/byggr/ByggrServiceTest.java
> UF-10514: Added env in error mails (+ sonar issue fixes)

- src/main/java/se/sundsvall/casemanagement/api/model/enums/Namespace.java
- src/main/java/se/sundsvall/casemanagement/integration/casedata/CaseDataService.java
- src/test/java/se/sundsvall/casemanagement/integration/casedata/CaseDataServiceTest.java
> UF-10518: Corrected namespaces for casedata integration

- src/main/java/se/sundsvall/casemanagement/util/Processor.java
> UF-10528: Fix build issue

- src/main/java/se/sundsvall/casemanagement/api/model/enums/FacilityType.java
> added two new facility types that are used in demolition cases

- src/main/java/se/sundsvall/casemanagement/integration/byggr/ByggrProcessor.java
- src/main/java/se/sundsvall/casemanagement/service/CaseService.java
- src/main/java/se/sundsvall/casemanagement/service/event/UpdateByggrCase.java
- src/test/java/se/sundsvall/casemanagement/integration/byggr/ByggrProcessorTest.java
> Changed put byggrcase logic to work asynchronously

- src/main/java/se/sundsvall/casemanagement/api/model/enums/Namespace.java
- src/main/java/se/sundsvall/casemanagement/integration/casedata/CaseDataService.java
- src/test/java/se/sundsvall/casemanagement/integration/casedata/CaseDataServiceTest.java
> UF-10632: Update namespace name

- src/main/resources/db/migration/V2_4__addCaseTypes.sql
> New case types

- src/main/java/se/sundsvall/casemanagement/integration/alkt/AlkTService.java
- src/test/java/se/sundsvall/casemanagement/integration/alkt/AlkTServiceTest.java
- src/test/java/se/sundsvall/casemanagement/integration/casedata/CaseDataServiceTest.java
> UF-11177: Fix sonar issue

- src/integration-test/resources/CaseStatusIT/__files/test11_getStatusesByPartyId/response.json
- src/integration-test/resources/CaseStatusIT/__files/test12_getStatusesByPartyId/response.json
- src/main/java/se/sundsvall/casemanagement/integration/alkt/AlkTService.java
> Updated alk-t service statuses

- src/integration-test/java/se/sundsvall/casemanagement/openapi/OpenApiSpecificationIT.java
- src/main/java/se/sundsvall/casemanagement/api/AttachmentResource.java
- src/main/java/se/sundsvall/casemanagement/api/CaseMappingResource.java
- src/main/java/se/sundsvall/casemanagement/api/CaseResource.java
- src/main/java/se/sundsvall/casemanagement/api/CaseStatusResource.java
- src/main/java/se/sundsvall/casemanagement/integration/casedata/CaseDataClient.java
- src/main/java/se/sundsvall/casemanagement/integration/citizen/CitizenClient.java
- src/main/java/se/sundsvall/casemanagement/integration/fb/FbClient.java
- src/main/java/se/sundsvall/casemanagement/integration/lantmateriet/RegisterbeteckningClient.java
- src/main/java/se/sundsvall/casemanagement/integration/messaging/MessagingClient.java
- src/main/resources/api/openapi.yaml
> UF-11518: Fix faulty reponsetypes

- src/main/java/se/sundsvall/casemanagement/api/model/StakeholderDTO.java
- src/main/java/se/sundsvall/casemanagement/api/model/enums/StakeholderRole.java
- src/main/java/se/sundsvall/casemanagement/api/validation/impl/EcosStakeholderRoleConstraintValidator.java
- src/main/java/se/sundsvall/casemanagement/integration/ecos/PartyService.java
- src/main/resources/api/openapi.yaml
- src/test/java/se/sundsvall/casemanagement/api/validation/EcosStakeholderRoleConstraintValidatorTest.java
> UF-14198: Remove deprecated stakeholder role

- README.md
> UF-11159: Add readme

- src/main/java/se/sundsvall/casemanagement/api/model/enums/Namespace.java
> UF-14554: Add new namespace

- src/main/java/se/sundsvall/casemanagement/integration/byggr/ByggrProcessor.java
- src/main/java/se/sundsvall/casemanagement/integration/byggr/ByggrService.java
- src/main/java/se/sundsvall/casemanagement/integration/casedata/CasedataProcessor.java
- src/main/java/se/sundsvall/casemanagement/integration/ecos/EcosProcessor.java
- src/main/java/se/sundsvall/casemanagement/util/EnvironmentUtil.java
- src/main/java/se/sundsvall/casemanagement/util/Processor.java
- src/test/java/se/sundsvall/casemanagement/integration/byggr/ByggrProcessorTest.java
- src/test/java/se/sundsvall/casemanagement/integration/byggr/ByggrServiceTest.java
Removed retry handling. Instead added the messaging integration to the error handling
> Error handling changes

- src/main/resources/integrations/rest/messaging.yml
> UF-14621: Update to messaging 6.1

- src/main/java/se/sundsvall/casemanagement/integration/party/PartyIntegration.java
- src/test/java/se/sundsvall/casemanagement/integration/party/PartyIntegrationTest.java
> UF-14741: Nullpointer in party integration

- src/integration-test/resources/CasedataIT/__files/test3_updateCase/mappings/CaseData_PatchStatusOnErrand_204.json
- src/main/java/se/sundsvall/casemanagement/integration/casedata/CaseDataClient.java
- src/main/java/se/sundsvall/casemanagement/integration/casedata/CaseDataService.java
- src/test/java/se/sundsvall/casemanagement/integration/casedata/CaseDataServiceTest.java
> Draken-1136: Changed put to patch call for updating status in CaseData

- src/integration-test/resources/CasedataIT/__files/test1_PostParkingPermitCase/mappings/casedata_postCase.json
- src/main/java/se/sundsvall/casemanagement/integration/casedata/CaseDataService.java
- src/test/java/se/sundsvall/casemanagement/integration/casedata/CaseDataServiceTest.java
> UF-15113: Fix for setting status of new errand in case-data

- src/integration-test/java/se/sundsvall/casemanagement/openapi/OpenApiSpecificationIT.java
- src/integration-test/resources/AttachmentsIT/__files/test5_InvalidRequest/response.json
- src/integration-test/resources/CaseStatusIT/__files/test10_getStatusesByPartyId/response.json
- src/integration-test/resources/CaseStatusIT/__files/test11_getStatusesByPartyId/response.json
- src/integration-test/resources/CaseStatusIT/__files/test12_getStatusesByPartyId/response.json
- src/integration-test/resources/CaseStatusIT/__files/test3_GetCaseDataStatusByExternalCaseId/response/CaseData_GetErrandWithId.json
- src/integration-test/resources/CaseStatusIT/__files/test5_getStatusesByPartyId/response.json
- src/integration-test/resources/CaseStatusIT/__files/test5_getStatusesByPartyId/responses/api-casedata-get-errands-namespace1.json
- src/integration-test/resources/CaseStatusIT/__files/test6_getStatusesByPartyId/response.json
- src/integration-test/resources/CaseStatusIT/__files/test6_getStatusesByPartyId/responses/api-casedata-get-errands-namespace2.json
- src/integration-test/resources/CaseStatusIT/__files/test7_getStatusesByPartyId/response.json
- src/integration-test/resources/CaseStatusIT/__files/test8_getStatusesByPartyId/response.json
- src/integration-test/resources/CaseStatusIT/__files/test9_getStatusesByPartyId/response.json
- src/integration-test/resources/CasedataIT/__files/test1_PostParkingPermitCase/mappings/casedata_postCase.json
- src/integration-test/resources/CasedataIT/__files/test1_PostParkingPermitCase/response/casedata_getCase.json
- src/integration-test/resources/CasedataIT/__files/test2_postCaseInternalError/response/casedata_getCase.json
- src/main/java/se/sundsvall/casemanagement/api/model/CaseDTO.java
- src/main/java/se/sundsvall/casemanagement/api/model/OtherCaseDTO.java
- src/main/resources/api/openapi.yaml
- src/test/java/se/sundsvall/casemanagement/api/model/OtherCaseDTOTest.java
* Classes weren't generating properly. Had to change some API documentation to work around the issue
> UF-15198 API Docs

- src/main/java/se/sundsvall/casemanagement/integration/byggr/ByggrService.java
- src/main/java/se/sundsvall/casemanagement/integration/messaging/MessagingClient.java
- src/test/java/se/sundsvall/casemanagement/integration/byggr/ByggrServiceTest.java
* Fixed bug that was sending the error message as the municipalityId to the slack integration
> UF-15347 Slack Bug fix

- src/main/java/se/sundsvall/casemanagement/api/model/enums/StakeholderRole.java
> DRAKEN-1307: add stakeholder role

- src/integration-test/resources/CasedataIT/__files/test4_PostParkingPermitCaseAndAnge/mappings/casedata_postCase.json
- src/main/java/se/sundsvall/casemanagement/integration/casedata/CaseDataService.java
- src/test/java/se/sundsvall/casemanagement/integration/casedata/CaseDataServiceTest.java
> UF-16085: Added an ADMINISTRATOR stakeholder to CD errands if AUTOMATIC.

- src/main/resources/application.yml
* Enabled dept44 default logger
> UF-16418 Enabled Dept44 Default Logger

- src/main/java/se/sundsvall/casemanagement/integration/byggr/ByggrService.java
- src/main/java/se/sundsvall/casemanagement/util/Processor.java
- src/test/java/se/sundsvall/casemanagement/integration/byggr/ByggrServiceTest.java
> UF-16937: set delivered to true when updating oep

- src/main/java/se/sundsvall/casemanagement/service/StatusService.java
> UF-17042: Optimize with async fetching of status

- src/main/java/se/sundsvall/casemanagement/service/StatusService.java
- src/test/java/se/sundsvall/casemanagement/service/StatusServiceTest.java
> UF-17042: pt2 parallelized calls for status 

- pom.xml
- src/integration-test/resources/CaseStatusIT/__files/test11_getStatusesByPartyId/mappings/api-casedata-get-errands-namespace1.json
- src/integration-test/resources/CaseStatusIT/__files/test11_getStatusesByPartyId/mappings/api-casedata-get-errands-namespace2.json
- src/integration-test/resources/CaseStatusIT/__files/test5_getStatusesByPartyId/mappings/api-casedata-get-errands-namespace1.json
- src/integration-test/resources/CaseStatusIT/__files/test5_getStatusesByPartyId/mappings/api-casedata-get-errands-namespace2.json
- src/integration-test/resources/CaseStatusIT/__files/test7_getStatusesByPartyId/mappings/api-casedata-get-errands-namespace1.json
- src/integration-test/resources/CaseStatusIT/__files/test7_getStatusesByPartyId/mappings/api-casedata-get-errands-namespace2.json
- src/integration-test/resources/CaseStatusIT/__files/test9_getStatusesByPartyId/mappings/api-casedata-get-errands-namespace1.json
- src/integration-test/resources/CaseStatusIT/__files/test9_getStatusesByPartyId/mappings/api-casedata-get-errands-namespace2.json
- src/main/java/se/sundsvall/casemanagement/service/StatusService.java
> UF-17231: Fixed spring filter bug

- src/main/java/se/sundsvall/casemanagement/integration/casedata/CaseDataService.java
- src/main/java/se/sundsvall/casemanagement/integration/casedata/configuration/CaseDataConfiguration.java
- src/main/java/se/sundsvall/casemanagement/integration/db/CaseTypeDataRepository.java
- src/main/java/se/sundsvall/casemanagement/integration/ecos/EcosService.java
- src/main/java/se/sundsvall/casemanagement/integration/fb/FbClient.java
- src/main/java/se/sundsvall/casemanagement/integration/lantmateriet/RegisterbeteckningClient.java
- src/main/java/se/sundsvall/casemanagement/util/Constants.java
> UF-17245: Fixed bug that cased NoSuchElementException
